import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme-provider';
import './globals.css';
import { roboto } from '@/config/fonts';
import { Toaster } from 'sonner';
import { Providers } from '@/components/layout/providers';

export const metadata: Metadata = {
  title: {
    template: '%s | Servicios Integrados',
    default: 'Servicios Integrados',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={roboto.className}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system">
            {children}
            <Toaster richColors />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
